twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        maps_api_key: '%env(MAPS_API_KEY)%'
        mail_from: '%env(MAIL_FROM)%'
        wedding_date: '%env(weddingdate)%'
        wedding_pot_url: '%env(weddingpoturl)%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'form/datepicker_widget.html.twig'