vich_uploader:
    db_driver: orm

    mappings:
        accommodations:
            uri_prefix: /images/hebergements
            upload_destination: '%kernel.project_dir%/public/images/hebergements'
        blog:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
